[profile.default]
src = 'contracts'
out = 'out'

fs_permissions = [{ access = "read-write", path = "./"}]

via_ir = true
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
bsc = "${BSC_RPC_URL}"
base = "${BASE_RPC_URL}"
base_goerli = "${BASE_GOERLI_RPC_URL}"
tenderly = "${TENDERLY_RPC_URL}"

[etherscan]
bsc = { key = "${BSC_SCAN_API_KEY}", url = "${BSC_ETHERSCAN_VERIFIER_URL}" }
base = { key = "${BASE_SCAN_API_KEY}", url = "${BASE_ETHERSCAN_VERIFIER_URL}" }
base_goerli = { key = "${BASE_GOERLI_SCAN_API_KEY}", url = "${BASE_GOERLI_ETHERSCAN_VERIFIER_URL}" }
